apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: olympiadas-kafka
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    storage:
      type: persistent-claim
      size: 10Gi
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi