services:
  python_service:
    build: .
    container_name: python_service
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/code/logs
    restart: always 
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug